### ISSUE TITLE
How can I use flux model?

### ISSUE THREAD

**Issue by K-O-N-B** [Acly/krita-ai-diffusion#1163]
My comfyui and webui shared all the checkpoints. Krita can found my SD5 and SDXL model. But flux con't. Local server mode.
![image](https://github.com/user-attachments/assets/66495dc1-3c73-460a-9b6f-4a493299a087)

![image](https://github.com/user-attachments/assets/55ad5e23-204b-4b8b-82cc-f47cf6b294de)

**Comment by yecai2024** [comment]
> Two things: One, the directory recently changed in ComfyUI from "unet" to "diffusion_models" so you should change the name of your folder. Two, you need to modify the file `.../ComfyUI/extra_model_paths.yaml` like so,
> 
> ```yaml
>     checkpoints: |
>          models/checkpoints
>          models/diffusion_models
> ```

Thank you so much for providing the solution! Could you please let me know which line I should place these code on? I tried putting it in the two positions indicated by the arrow, but my ComfyUI wouldn't start after that. Could I see a screenshot of your file?
![Q9112](https://github.com/user-attachments/assets/cda633d6-16bb-452e-88b2-32d50a70184f)

**Comment by creeduk** [comment]
Can the extension stay as sft or do we need a symlink from sft to safetensors?

**Comment by mvstrawn** [comment]
@yecai2024 Well I used A1111 before CUI, so my file will look a little different if you didn't do the same, but here is how mine is done:

```yaml
#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a1111:
    base_path: /opt/stable-diffusion-web-ui/

    checkpoints: |
         /games/.sd-models/Stable-diffusion
         /games/.sd-models/diffusion_models
    diffusion_models:
         /games/.sd-models/diffusion_models
    configs: /games/.sd-models/Stable-diffusion
    vae: /games/.sd-models/VAE
    vae_approx: /games/.sd-models/VAE-approx
    loras: |
         /games/.sd-models/Lora
         /games/.sd-models/LyCORIS
    upscale_models: |
                  /games/.sd-models/ESRGAN
                  /games/.sd-models/RealESRGAN
                  /games/.sd-models/SwinIR
    embeddings: /games/.sd-models/embeddings
    hypernetworks: /games/.sd-models/hypernetworks
    controlnet: /games/.sd-models/ControlNet
    clip: /games/.sd-models/clip
```

@creeduk I think the process of detecting valid Flux models is more complex than that. I made a comment about it in another issue here but I don't recall where. Regardless, I have multiple Flux models in my directory, some of which are picked up by the plugin and some of which are not (all of them are usable in CUI however), so I'm not sure how to handle that.
