### ISSUE TITLE
flux missing after update

### ISSUE THREAD

**Issue by marcoA152** [Acly/krita-ai-diffusion#1395]
if you have flux running from unet folder, add 

```
krita-managed:
    base_path: ../models
    checkpoints: checkpoints
    clip: clip
    clip_vision: clip_vision
    controlnet: controlnet
    diffusion_models: diffusion_models
    embeddings: embeddings
    inpaint: inpaint
    ipadapter: ipadapter
    loras: loras
    upscale_models: upscale_models
    vae: vae
    unet: unet  #this line

```
at the end of extra_model_paths.yaml file

simply moving flux1-dev.safetensors to checkpoints folder do not works...
